//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WpfApp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book &quot;{0}&quot; ({1} pages) added..
        /// </summary>
        internal static string Message_Book__0__1__pages__added {
            get {
                return ResourceManager.GetString("Message_Book__0__1__pages__added", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot perform operation.
        /// </summary>
        internal static string Message_Cannot_perform_operation {
            get {
                return ResourceManager.GetString("Message_Cannot_perform_operation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot save settings to file..
        /// </summary>
        internal static string Message_Cannot_save_settings_to_file {
            get {
                return ResourceManager.GetString("Message_Cannot_save_settings_to_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initialization completed..
        /// </summary>
        internal static string Message_Initialization_completed {
            get {
                return ResourceManager.GetString("Message_Initialization_completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initialization started..
        /// </summary>
        internal static string Message_Initialization_started {
            get {
                return ResourceManager.GetString("Message_Initialization_started", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugin {0} finished.
        /// </summary>
        internal static string Message_Plugin__0__finished {
            get {
                return ResourceManager.GetString("Message_Plugin__0__finished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugin {0} is starting.
        /// </summary>
        internal static string Message_Plugin__0__is_starting {
            get {
                return ResourceManager.GetString("Message_Plugin__0__is_starting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings were updated..
        /// </summary>
        internal static string Message_Settings_were_updated {
            get {
                return ResourceManager.GetString("Message_Settings_were_updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected error occured..
        /// </summary>
        internal static string Message_Unexpected_error_occured {
            get {
                return ResourceManager.GetString("Message_Unexpected_error_occured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Title_Error {
            get {
                return ResourceManager.GetString("Title_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        internal static string Title_Info {
            get {
                return ResourceManager.GetString("Title_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string Title_Warning {
            get {
                return ResourceManager.GetString("Title_Warning", resourceCulture);
            }
        }
    }
}
